language: ruby

env:
  global:
    - secure: "WL7IM06BiJ8+bDlLdb17mSRbuQm8RUr1BS1BHfL9vkXrF3j30XO1ellhq53w8WdFUxmWtZTC6BQklRI2ZmEgemkIT1w/6a3G8vMs7thR5V1/zitymsMYKlvyBdzgSZ2crPxORFivQ+cbsoXJcWoY8SL180eJlLQct6dqFU/Wx7kxVEGMAcBbkCoLi6UlvLCpNoDOVjmH4fL1nLvbPcNOMca/+zi5zlvBlIarj92ZyP+OwIDQIi6FZRxC4L+qlxjWGjS1vxiohjGWOSfyEdj9zxC3XG4ap7yinMmx2yNEpeyhUt3J/psr4Q+WIpaCaf4RARlcKa4zO2yNfF7d5IIBOh0Qi/8y2XklWvhSz6u9+AsQVw998swV+nTlT8oINWjVpz9rS6UjB2by7lnwJ6epXNOoMNt1SS/3I3xsZjU9cuKBbu5fRr76KAuCC7cOwailww+vxh2lNrtepmE16FpilY34j9N3sIr7xyLe2lFamgQHCBb1hbr7/PIfHbpAvjjG/VeaA8Bh/6bs5zehjqhpIy6FifN4n0LZ5zyeT6drXuKI7lz+tec3mMh6tM3aXBY5SUcV/2yq5VfT7KVMZGG4qjuf5iOqxJ+XZr2XOlmGUXhE8k/NLQGYEb60x1NOGnkMWw0DFNc8+CGtyhz8gzVR38moZE8fpUE6cvAfDSrvhq4="
    - secure: "SvF6TmZMj1LBWp0ebity9nB3PPyIF4wCTREbYRAhWHE5gOBYEOpt5UdUUJFQADb2nlBXtjmX0DDgX+SoPDJKFta1NDaEB877xAfWcm3KXBfo3g1Q+2bkVYEpPTXL7CE+C+Uu5vhIRloC6aNJ6iJIFjPTTPlCcr8gtxgT+Qu8PQww2lctAexOlualtza9SBSwB2OOxxtCOBAFyK/Nj5Pr3IShoqlXTtKD2u8Pr6Pe5jIwDdcll+PGU238EEqFr8KAfAmLQvNbyKULYLu8vb4tlWdUteTrQo0FzXdcitCrKElhdfQuVZDz6gzXVD85vbV2QIRcPEQZ5H2LEbPsoFK8sJU7WXV4xAMpmcnm2ZBrghywt9P54+WXt5L8eTX389krCpimGOjXjWZI+HD08UIPzHSDsbhTQ40BudT1IdvZUpVqbTv6MytaSEdk+Qt0ZIvWmNgGmTwOSYk74FlH3it04XQXpuq/8v8wLobIzxJsJGCDmXr9c+wehdgRMLEYXP6g/t5ZWmXYH29L1v9+g18Cny/QSIHob35ocfw39a2ThwkofXv8VvTA3Q2AAxlu5/PGWJuI84KNgHvW0hyQ7GMwjmmfhwTutZIWgpjyH3qCBEvSDhuK0uKF8CFV5dTYaYPmzm1ElY1ERUSsqVKLb4TWOgdQLF1Lxawgh3Pzn4w2pHA="

stages:
  - docker

jobs:
  include:
    - stage: docker

      language: ruby

      services:
        - docker

      before_script:
        - docker --version

      script:
        - docker build --tag localheinz/composer-normalize-action .
        - docker run --interactive --rm --tty --workdir=/normalizer --volume ${PWD}:/normalizer localheinz/composer-normalize-action:latest

      deploy:
        on:
          branch: master
        provider: script
        skip_cleanup: false
        script: echo "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME" &&  docker push localheinz/composer-normalize-action

notifications:
  email: false
