language: ruby

stages:
  - build

jobs:
  include:
    - stage: build

      language: ruby

      services:
        - docker

      before_script:
        - docker --version

      script:
        - docker build --tag localheinz/composer-normalize-action .
        - docker run --interactive --rm --tty --workdir=/normalizer --volume ${PWD}:/normalizer localheinz/composer-normalize-action:latest

notifications:
  email: false
